<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Vehicle Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            margin: 0;
            padding: 20px;
            color: #000;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #007bff;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .header h2 {
            margin: 0;
            color: #007bff;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        .report-details {
            margin-bottom: 15px;
            font-size: 13px;
        }
        .report-details p {
            margin: 3px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 13px;
        }
        th, td {
            border: 1px solid #444;
            padding: 8px;
            text-align: center;
        }
        thead {
            background: #e3f2fd;
            font-weight: bold;
        }
        tfoot {
            background: #e8f5e9;
            font-weight: bold;
        }
        .footer {
            width: 100%;
            border-top: 1px solid #ccc;
            margin-top: 30px;
            padding-top: 10px;
            font-size: 12px;
            color: #555;
        }
        .footer-left {
            float: left;
        }
        .footer-right {
            float: right;
        }
        .clearfix::after {
            content: "";
            display: table;
            clear: both;
        }
    </style>
</head>
<body>
    {{-- Header --}}
    <div class="header">
        <h2>Daily Report Summary</h2>
    </div>

    {{-- Date Range --}}
    <div class="report-details">
        <p><strong>From Date:</strong> 
            {{ $from_date ? \Carbon\Carbon::parse($from_date)->format('d M Y') : 'N/A' }}
        </p>
        <p><strong>To Date:</strong> 
            {{ $to_date ? \Carbon\Carbon::parse($to_date)->format('d M Y') : 'N/A' }}
        </p>
    </div>

    {{-- Data Table --}}
    <table>
        <thead>
            <tr>
                <th>SR NO</th>
                <th>VEHICLE TYPE</th>
                <th>QTY</th>
                <th>AMOUNT</th>
            </tr>
        </thead>
        <tbody>
            @php
                $grandQty = $reports->sum('qty');
                $grandAmount = $reports->sum('total_amount');
            @endphp

            @forelse($reports as $key => $report)
                <tr>
                    <td>{{ $key + 1 }}</td>
                    <td>{{ $report['vehicle_type'] }}</td>
                    <td>{{ $report['qty'] }}</td>
                    <td>{{ number_format($report['total_amount'], 2) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="4" style="color:red;">No records found</td>
                </tr>
            @endforelse
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2">Grand Total</td>
                <td>{{ $grandQty }}</td>
                <td>{{ number_format($grandAmount, 2) }}</td>
            </tr>
        </tfoot>
    </table>

    {{-- Footer --}}
    <div class="footer clearfix">
        <div class="footer-left">
            © {{ date('Y') }} | Generated by {{ auth()->user()->name ?? 'System' }}
        </div>
        <div class="footer-right">
            Generated on: {{ now()->format('d M Y') }}
        </div>
    </div>
</body>
</html>
