<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>User Report PDF</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            margin: 0;
            padding: 20px;
            color: #000;
            font-size: 13px;
        }

        .header {
            text-align: center;
            border-bottom: 2px solid #007bff;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }

        .header h2 {
            margin: 0;
            color: #007bff;
            text-transform: uppercase;
            letter-spacing: 1px;
        }

        .report-details {
            margin-bottom: 15px;
            text-align: center;
            font-weight: bold;
            font-size: 14px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 13px;
        }

        th,
        td {
            border: 1px solid #444;
            padding: 8px;
            text-align: center;
        }

        thead {
            background: #e3f2fd;
            font-weight: bold;
        }

        tfoot {
            background: #e8f5e9;
            font-weight: bold;
        }

        .footer {
            width: 100%;
            border-top: 1px solid #ccc;
            margin-top: 30px;
            padding-top: 10px;
            font-size: 12px;
            color: #555;
        }

        .footer-left {
            float: left;
        }

        .footer-right {
            float: right;
        }

        .clearfix::after {
            content: "";
            display: table;
            clear: both;
        }

        .no-record {
            color: red;
            text-align: center;
            font-weight: bold;
            margin-top: 30px;
        }
    </style>
</head>

<body>
    {{-- Header --}}
    <div class="header">
        <h2>User Report Summary</h2>
    </div>

    {{-- Date Range (show based on input values if exist) --}}
    <div class="report-details">
        @php
            // Grab the form input values (if any)
            $from_date = request('from_date');
            $to_date = request('to_date');
        @endphp

        @if ($from_date && $to_date)
            From <strong>{{ \Carbon\Carbon::parse($from_date)->format('d M Y') }}</strong>
            to <strong>{{ \Carbon\Carbon::parse($to_date)->format('d M Y') }}</strong>
        @elseif ($from_date)
            From <strong>{{ \Carbon\Carbon::parse($from_date)->format('d M Y') }}</strong> onwards
        @elseif ($to_date)
            Till <strong>{{ \Carbon\Carbon::parse($to_date)->format('d M Y') }}</strong>
        @else
            <span>All Records</span>
        @endif
    </div>

    {{-- Report Table --}}
    @if ($report->isEmpty())
        <p class="no-record">⚠️ No records found for the selected date range.</p>
    @else
        @php
            $grandQty = $report->sum('vehicle_count');
            $grandAmount = $report->sum('total_amount');
        @endphp

        <table>
            <thead>
                <tr>
                    <th>SR NO</th>
                    <th>VEHICLE TYPE</th>
                    <th>USER NAME</th>
                    <th>QTY</th>
                    <th>AMOUNT (₹)</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($report as $key => $item)
                    <tr>
                        <td>{{ $key + 1 }}</td>
                        <td>{{ $item->vehicle->vehicle_type ?? 'N/A' }}</td>
                        <td>{{ $item->pos_user_name }}</td>
                        <td>{{ $item->vehicle_count }}</td>
                        <td>{{ number_format($item->total_amount, 2) }}</td>
                    </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3">Grand Total</td>
                    <td>{{ $grandQty }}</td>
                    <td>{{ number_format($grandAmount, 2) }}</td>
                </tr>
            </tfoot>
        </table>
    @endif

    {{-- Footer --}}
    <div class="footer clearfix">
        <div class="footer-left">
            © {{ date('Y') }} | Generated by {{ auth()->user()->name ?? 'System' }}
        </div>
        <div class="footer-right">
            Generated on: {{ now()->format('d M Y') }}
        </div>
    </div>

</body>

</html>
